/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.perforacion;

import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import reportes.leePlantilla;
import vistas.home;

/**
 *
 * @author User
 */
public class infoPerforacion extends javax.swing.JFrame {

    /**
     * Creates new form infoPerforacion
     */
    public infoPerforacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        getDatos();

    }

    public void getDatos() {
        Preferences prefs = Preferences.userNodeForPackage(infoPerforacion.class);

        String ubiPozo = prefs.get("ubiPozo", " ");
        String activdadEqui = prefs.get("activdadEqui", " ");
        String fechaIni = prefs.get("fechaIni", " ");
       // String fehaFin = prefs.get("fehaFin", " ");
        String compaIns = prefs.get("compaIns", " ");
        String nameSuper = prefs.get("nameSuper", " ");
        String celSuper = prefs.get("celSuper", " ");
        String nameAsis = prefs.get("nameAsis", " ");
        String celAsis = prefs.get("celAsis", " ");
        String nameInspect = prefs.get("nameInspect", " ");
        String celInspect = prefs.get("celInspect", " ");
        ubicacionPozotxt.setText(ubiPozo);
        actividadtxt.setText(activdadEqui);
       // fechaInitxt.setText(fechaIni);
        compniaIspectxt.setText(compaIns);
        nombreSupertxt.setText(nameSuper);
        celSuperTxt.setText(celSuper);
        nombreSupertxt.setText(nameAsis);
        celAsistxt.setText(celAsis);
        nameInspecttxt.setText(nameInspect);
        celInspecttxt.setText(celInspect);
        //fechafintxt.setText(fechafin)

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        celInspecttxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        celAsistxt = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        celSuperTxt = new javax.swing.JTextField();
        nombreSupertxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameInspecttxt = new javax.swing.JTextField();
        nombreAsistxt = new javax.swing.JTextField();
        ubicacionPozotxt = new javax.swing.JTextField();
        actividadtxt = new javax.swing.JTextField();
        compniaIspectxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("INICIO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 40, 20));

        jLabel9.setText("ACTIVIDAD ACTUAL DEL EQUIPO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, 20));

        jLabel14.setText("FECHA DE INSPECCION");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 140, 20));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("NOMBRE");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 77, 20));

        jLabel18.setText("FIN");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 26, 20));

        jLabel19.setText("COMPAÑIA INSPECTORA");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("SUPERVISOR DE INSPECCION ");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 32));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("UBICACION ACTUAL DEL POZO");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 182, 20));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CELULAR");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 77, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel26.setText("INSPECTOR");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 242, -1, 20));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("NOMBRE");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 77, 20));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("CELULAR");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 229, 77, 0));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CELULAR");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 70, 20));

        celInspecttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celInspecttxtActionPerformed(evt);
            }
        });
        jPanel2.add(celInspecttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 160, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("ASISTENTE SUPERVISOR DE INSPECCION ");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 32));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("NOMBRE");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 77, 20));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("CELULAR");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 60, 20));

        celAsistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celAsistxtActionPerformed(evt);
            }
        });
        jPanel2.add(celAsistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 160, -1));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 40, 40));

        celSuperTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celSuperTxtActionPerformed(evt);
            }
        });
        jPanel2.add(celSuperTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, -1));

        nombreSupertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSupertxtActionPerformed(evt);
            }
        });
        jPanel2.add(nombreSupertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("INFORMACIÓN PERFORACIÓN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        nameInspecttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInspecttxtActionPerformed(evt);
            }
        });
        jPanel2.add(nameInspecttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, -1));

        nombreAsistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAsistxtActionPerformed(evt);
            }
        });
        jPanel2.add(nombreAsistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, -1));

        ubicacionPozotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionPozotxtActionPerformed(evt);
            }
        });
        jPanel2.add(ubicacionPozotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 170, -1));

        actividadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actividadtxtActionPerformed(evt);
            }
        });
        jPanel2.add(actividadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 170, -1));

        compniaIspectxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compniaIspectxtActionPerformed(evt);
            }
        });
        jPanel2.add(compniaIspectxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 170, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 320, 110, -1));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 320, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celInspecttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celInspecttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celInspecttxtActionPerformed

    private void celAsistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celAsistxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celAsistxtActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Preferences prefs = Preferences.userNodeForPackage(infoPerforacion.class);

        prefs.put("ubiPozo", ubicacionPozotxt.getText());
        prefs.put("activdadEqui", actividadtxt.getText());
       // prefs.put("fechaIni", fechaInitxt.getText());
       //prefs.put("fehaFin", fechafintxt.getText());
        prefs.put("compaIns", compniaIspectxt.getText());
        prefs.put("nameSuper", nombreSupertxt.getText());
        prefs.put("celSuper", celSuperTxt.getText());
        prefs.put("nameAsis", nombreSupertxt.getText());
        prefs.put("celAsis", celAsistxt.getText());
        prefs.put("nameInspect", nameInspecttxt.getText());
        prefs.put("celInspect", celInspecttxt.getText());
        
        JOptionPane.showMessageDialog(null, "Datos Guardados");
        tipoInspeccion p = new tipoInspeccion();
         p.setVisible(true);
         this.setVisible(false);
     


    }//GEN-LAST:event_nextActionPerformed

    private void nombreSupertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSupertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSupertxtActionPerformed

    private void celSuperTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celSuperTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celSuperTxtActionPerformed

    private void nameInspecttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInspecttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInspecttxtActionPerformed

    private void nombreAsistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAsistxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAsistxtActionPerformed

    private void ubicacionPozotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionPozotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionPozotxtActionPerformed

    private void actividadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actividadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actividadtxtActionPerformed

    private void compniaIspectxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compniaIspectxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compniaIspectxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        presenteadoA p = new presenteadoA();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoPerforacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoPerforacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoPerforacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoPerforacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoPerforacion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actividadtxt;
    private javax.swing.JTextField celAsistxt;
    private javax.swing.JTextField celInspecttxt;
    private javax.swing.JTextField celSuperTxt;
    private javax.swing.JTextField compniaIspectxt;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameInspecttxt;
    private javax.swing.JButton next;
    private javax.swing.JTextField nombreAsistxt;
    private javax.swing.JTextField nombreSupertxt;
    private javax.swing.JTextField ubicacionPozotxt;
    // End of variables declaration//GEN-END:variables
}
