/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.perforacion;

import java.util.prefs.Preferences;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import reportes.leePlantilla;

/**
 *
 * @author User
 */
public class tipoInsepeccionThree extends javax.swing.JFrame {

    /**
     * Creates new form tipoInspeccion
     */
    public tipoInsepeccionThree() {
        initComponents();
        this.setLocationRelativeTo(null);
        getDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        nextbtn10 = new javax.swing.JButton();
        Perf2txt10 = new javax.swing.JCheckBox();
        Wk2txt10 = new javax.swing.JCheckBox();
        Perf1txt10 = new javax.swing.JCheckBox();
        Wk1txt10 = new javax.swing.JCheckBox();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel198.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel198.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel198.setText("WK");
        jPanel13.add(jLabel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 20, 20));

        jLabel199.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel199.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel199.setText("PERF");
        jPanel13.add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 60, 20));

        jLabel200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel200.setText("CELULAR");
        jPanel13.add(jLabel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 229, 77, 0));

        jLabel201.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel201.setText("INTERNACIONAL");
        jPanel13.add(jLabel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 32));

        jLabel202.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel202.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel202.setText("NIVEL DE INSPECCION");
        jPanel13.add(jLabel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 182, 32));

        jLabel203.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel203.setText("NACIONAL");
        jPanel13.add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, 32));

        jLabel204.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel204.setText("-EVALUACIÓN DE RIESGOS E INVESTIGACIÓN DE ACCIDENTES/INCIDENTES");
        jPanel13.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 420, 32));

        nextbtn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        nextbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtn10nextbtn1ActionPerformed(evt);
            }
        });
        jPanel13.add(nextbtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        Perf2txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Perf2txt10Perf2txt1ActionPerformed(evt);
            }
        });
        jPanel13.add(Perf2txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        Wk2txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wk2txt10Wk2txt1ActionPerformed(evt);
            }
        });
        jPanel13.add(Wk2txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        Perf1txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Perf1txt10Perf1txt1ActionPerformed(evt);
            }
        });
        jPanel13.add(Perf1txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        Wk1txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wk1txt10Wk1txt1ActionPerformed(evt);
            }
        });
        jPanel13.add(Wk1txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel205.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel205.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel205.setText("WK");
        jPanel13.add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 20, 20));

        jLabel206.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel206.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel206.setText("PERF");
        jPanel13.add(jLabel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 60, 20));

        jButton1.setText("Volver");
        jPanel13.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextbtn10nextbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtn10nextbtn1ActionPerformed
        Preferences prefs = Preferences.userNodeForPackage(tipoInspeccion.class);

        int perf1, perf2, wk1, wk2;

        perf1 = (Perf1txt10.isSelected()) ? 1 : 0;
        perf2 = (Perf2txt10.isSelected()) ? 1 : 0;

        wk1 = (Wk1txt10.isSelected()) ? 1 : 0;
        wk2 = (Wk2txt10.isSelected()) ? 1 : 0;

        prefs.putInt("ERIAI1", perf1);
        prefs.putInt("ERIAI3", perf2);
        prefs.putInt("ERIAI2", wk1);
        prefs.putInt("ERIAI4", wk2);

  

        JOptionPane.showMessageDialog(null, "Datos Guardados");
        this.setVisible(false);
    }//GEN-LAST:event_nextbtn10nextbtn1ActionPerformed

    private void Perf2txt10Perf2txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Perf2txt10Perf2txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Perf2txt10Perf2txt1ActionPerformed

    private void Wk2txt10Wk2txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wk2txt10Wk2txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Wk2txt10Wk2txt1ActionPerformed

    private void Perf1txt10Perf1txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Perf1txt10Perf1txt1ActionPerformed
        System.out.println("me selecciono");
    }//GEN-LAST:event_Perf1txt10Perf1txt1ActionPerformed

    private void Wk1txt10Wk1txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wk1txt10Wk1txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Wk1txt10Wk1txt1ActionPerformed
    private void getDatos() {
        Preferences prefs = Preferences.userNodeForPackage(tipoInsepeccionTwo.class);
        selectedCheck(Perf1txt10, prefs.getInt("ERIAI1", 0));
        selectedCheck(Perf2txt10, prefs.getInt("ERIAI3", 0));
        selectedCheck(Wk1txt10, prefs.getInt("ERIAI2", 0));
        selectedCheck(Wk2txt10, prefs.getInt("ERIAI4", 0));

    }

    private void selectedCheck(JCheckBox j, int value) {
        if (value == 1) {
            j.setSelected(true);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipoInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipoInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipoInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipoInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipoInspeccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Perf1txt10;
    private javax.swing.JCheckBox Perf2txt10;
    private javax.swing.JCheckBox Wk1txt10;
    private javax.swing.JCheckBox Wk2txt10;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JButton nextbtn10;
    // End of variables declaration//GEN-END:variables
}
